# Generated by Django 2.1.1 on 2018-09-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_internationalfaculty_nationalfaculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internationalfaculty',
            name='cv',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to='faculties/cv'),
        ),
        migrations.AlterField(
            model_name='internationalfaculty',
            name='image',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to='faculties'),
        ),
    ]
