# Generated by Django 2.1.3 on 2018-11-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20181123_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anasthesiafaculty',
            old_name='name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='hepatologyfaculty',
            old_name='name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='surgeryfaculty',
            old_name='name',
            new_name='ffname',
        ),
        migrations.AddField(
            model_name='anasthesiafaculty',
            name='lname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hepatologyfaculty',
            name='lname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='surgeryfaculty',
            name='lname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
