# Generated by Django 2.1.3 on 2018-11-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20181128_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internationalfaculty',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='internationalfaculty',
            name='lname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
