# Generated by Django 2.1.3 on 2018-11-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20181128_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surgeryfaculty',
            old_name='ffname',
            new_name='fname',
        ),
    ]
