# Generated by Django 2.1.3 on 2018-12-08 08:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_downloads_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2018, 12, 8, 8, 51, 50, 44704, tzinfo=utc))),
                ('time_range', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('venue', models.CharField(max_length=150)),
                ('speaker', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
