# Generated by Django 2.1.3 on 2018-12-13 08:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20181208_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 12, 13, 8, 4, 21, 487739, tzinfo=utc)),
        ),
    ]
