# Generated by Django 2.1.3 on 2018-12-18 05:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20181214_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 12, 18, 5, 41, 59, 765338, tzinfo=utc)),
        ),
    ]
