# Generated by Django 2.1.3 on 2018-12-18 05:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_auto_20181218_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
