# Generated by Django 2.1.3 on 2019-01-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20190122_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda15',
            name='time_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agenda16',
            name='time_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agenda17',
            name='time_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agenda172',
            name='time_range',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
