# Generated by Django 2.1.5 on 2019-01-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20190122_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda15',
            name='dp',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda16',
            name='dp',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda17',
            name='dp',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda172',
            name='dp',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
