# Generated by Django 2.1.5 on 2019-01-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_auto_20190125_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda15',
            name='single',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda16',
            name='single',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda17',
            name='single',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agenda172',
            name='single',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
