# Generated by Django 2.1.5 on 2019-02-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_sponsors'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsors',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
