# Generated by Django 2.1.1 on 2018-09-20 11:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=4)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(default='Male', max_length=10)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('accompanying_title', models.CharField(blank=True, max_length=4, null=True)),
                ('accompanying_name', models.CharField(blank=True, max_length=150, null=True)),
                ('accompanying_age', models.IntegerField(default=0)),
                ('accompanying_gender', models.CharField(default='Male', max_length=15)),
                ('accompanying_registration_number', models.CharField(blank=True, max_length=150, null=True)),
                ('mode_of_payment', models.CharField(blank=True, max_length=25, null=True)),
                ('txnid', models.CharField(blank=True, max_length=25, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
