# Generated by Django 2.1.1 on 2018-09-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20180920_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='accompany',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Is someone accompanying you?'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='plan',
            field=models.IntegerField(blank=True, choices=[(1, 'Workshop (Delegate)'), (2, 'Workshop (Trainee)'), (3, 'Delegate (National)'), (4, 'Trainees (National)')], null=True, verbose_name='Choose your registration type'),
        ),
    ]
