# Generated by Django 2.1.1 on 2018-09-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20180920_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='accompanying_registration_number',
        ),
        migrations.AddField(
            model_name='registration',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='hospital',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
