# Generated by Django 2.1.3 on 2018-11-19 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_auto_20180925_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='speciality',
            field=models.CharField(blank=True, choices=[('Surgery', 'Surgery'), ('Hepatology', 'Hepatology'), ('Anesthesia', 'Anesthesia'), ('Critical Care', 'Critical Care'), ('Others', 'Others')], max_length=50, null=True),
        ),
    ]
