# Generated by Django 2.1.3 on 2018-12-05 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_registration_speciality'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnesthesiaRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(choices=[('Dr.', 'Dr.'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Sir', 'Sir')], max_length=4)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=200)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('hospital', models.CharField(blank=True, max_length=50, null=True)),
                ('speciality', models.CharField(blank=True, choices=[('Surgery', 'Surgery'), ('Hepatology', 'Hepatology'), ('Anesthesia', 'Anesthesia'), ('Critical Care', 'Critical Care'), ('Others', 'Others')], max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Medical Council Registration Number')),
                ('accompany', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Is someone accompanying you?')),
                ('accompanying_title', models.CharField(blank=True, choices=[('Dr.', 'Dr.'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Sir', 'Sir')], max_length=4, null=True, verbose_name='Accompanying Person Title')),
                ('accompanying_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Name of Accompanying Person, if any')),
                ('accompanying_age', models.IntegerField(default=0, verbose_name='Age of Accompanying Person, if any')),
                ('accompanying_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=15, verbose_name='Gender of accompanying person, if any')),
                ('mode_of_payment', models.CharField(blank=True, max_length=25, null=True)),
                ('txnid', models.CharField(blank=True, max_length=25, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=25, null=True)),
                ('plan', models.IntegerField(blank=True, choices=[(1, 'Workshop (Delegate)'), (2, 'Workshop (Trainee)'), (3, 'Delegate (National)'), (4, 'Trainees (National)')], null=True, verbose_name='Choose your registration type')),
            ],
        ),
    ]
