# Generated by Django 2.1.3 on 2018-12-13 08:04

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_anesthesiaregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('author1_name', models.CharField(blank=True, max_length=150, null=True)),
                ('author1_email', models.CharField(blank=True, max_length=150, null=True)),
                ('author1_institution', models.CharField(blank=True, max_length=150, null=True)),
                ('author1_specialisation', models.CharField(blank=True, max_length=150, null=True)),
                ('author2_name', models.CharField(blank=True, max_length=150, null=True)),
                ('author2_email', models.CharField(blank=True, max_length=150, null=True)),
                ('author2_institution', models.CharField(blank=True, max_length=150, null=True)),
                ('author2_specialisation', models.CharField(blank=True, max_length=150, null=True)),
                ('author3_name', models.CharField(blank=True, max_length=150, null=True)),
                ('author3_email', models.CharField(blank=True, max_length=150, null=True)),
                ('author3_institution', models.CharField(blank=True, max_length=150, null=True)),
                ('author3_specialisation', models.CharField(blank=True, max_length=150, null=True)),
                ('author4_name', models.CharField(blank=True, max_length=150, null=True)),
                ('author4_email', models.CharField(blank=True, max_length=150, null=True)),
                ('author4_institution', models.CharField(blank=True, max_length=150, null=True)),
                ('author4_specialisation', models.CharField(blank=True, max_length=150, null=True)),
                ('author5_name', models.CharField(blank=True, max_length=150, null=True)),
                ('author5_email', models.CharField(blank=True, max_length=150, null=True)),
                ('author5_institution', models.CharField(blank=True, max_length=150, null=True)),
                ('author5_specialisation', models.CharField(blank=True, max_length=150, null=True)),
                ('title', models.CharField(max_length=150)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
