# Generated by Django 2.1.3 on 2018-12-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_abstractsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractsubmission',
            name='author1_name',
            field=models.CharField(blank=True, help_text="First author's name", max_length=150, null=True),
        ),
    ]
