# Generated by Django 2.1.3 on 2018-12-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_auto_20181218_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anesthesiaregistration',
            name='speciality',
            field=models.CharField(blank=True, choices=[('Surgery', 'Surgery'), ('Hepatology', 'Hepatology'), ('Anesthesia', 'Anesthesia'), ('Critical Care', 'Critical Care'), ('Pathology', 'Pathology'), ('Radiology', 'Radiology'), ('Others', 'Others')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='plan',
            field=models.IntegerField(choices=[(1, 'Conference (Delegate)'), (2, 'Conference (Trainee)'), (3, 'Conference + Workshop (Delegate)'), (4, 'Conference + Workshop (Trainee)')], default=1, verbose_name='Choose your registration type'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='speciality',
            field=models.CharField(blank=True, choices=[('Surgery', 'Surgery'), ('Hepatology', 'Hepatology'), ('Anesthesia', 'Anesthesia'), ('Critical Care', 'Critical Care'), ('Pathology', 'Pathology'), ('Radiology', 'Radiology'), ('Others', 'Others')], max_length=50, null=True),
        ),
    ]
