# Generated by Django 2.1.3 on 2019-01-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20181231_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='anesthesiaregistration',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Passport number is required for foreign attendees'),
        ),
        migrations.AddField(
            model_name='registration',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Passport number is required for foreign attendees'),
        ),
    ]
